<!--

    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<testng-results>
  <reporter-output>
  </reporter-output>
  <suite name="Ant suite">
    <groups>
    </groups>
    <test name="Ant test">
      <class name="test.FailPassSkipTest">
        <test-method status="FAIL" signature="bTest()" name="bTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at test.FailPassSkipTest.bTest(FailPassSkipTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:580)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:478)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:617)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:885)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:110)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.TestNG.privateMain(TestNG.java:860)
	at org.testng.TestNG.main(TestNG.java:833)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="SKIP" signature="cTest()" name="cTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" depends-on-methods="test.FailPassSkipTest.aTest, test.FailPassSkipTest.bTest" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="aTest()" name="aTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
      </class>
      <class name="test.PassSkipTest">
        <test-method status="PASS" signature="setUp()" name="setUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="cleanUp()" name="cleanUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="aTest()" name="aTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="SKIP" signature="bTest()" name="bTest" duration-ms="0" depends-on-groups="xxx" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method test.PassSkipTest.bTest() depends on nonexistent group "xxx"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method test.PassSkipTest.bTest() depends on nonexistent group "xxx"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:964)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:110)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.TestNG.privateMain(TestNG.java:860)
	at org.testng.TestNG.main(TestNG.java:833)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
      <class name="test.CleanUpTest">
        <test-method status="FAIL" signature="cleanUp()" name="cleanUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[some message]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: some message
	at test.CleanUpTest.cleanUp(CleanUpTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:580)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:398)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:145)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:82)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:210)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:113)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.TestNG.privateMain(TestNG.java:860)
	at org.testng.TestNG.main(TestNG.java:833)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="aTest()" name="aTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="setUp()" name="setUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
      </class>
      <class name="test.FailingTest">
        <test-method status="FAIL" signature="aTest()" name="aTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at test.FailingTest.aTest(FailingTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:580)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:478)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:617)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:885)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:110)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.TestNG.privateMain(TestNG.java:860)
	at org.testng.TestNG.main(TestNG.java:833)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="FAIL" signature="bTest()" name="bTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Expected an exception in test method test.FailingTest.bTest()]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException:
Expected an exception in test method test.FailingTest.bTest()
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1122)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:898)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:110)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.TestNG.privateMain(TestNG.java:860)
	at org.testng.TestNG.main(TestNG.java:833)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="setUp()" name="setUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="cleanUp()" name="cleanUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="cTest()" name="cTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[catch this]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: catch this
	at test.FailingTest.cTest(FailingTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:580)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:478)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:617)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:885)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:110)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.TestNG.privateMain(TestNG.java:860)
	at org.testng.TestNG.main(TestNG.java:833)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
      <class name="test.NewTestNGTest">
        <test-method status="PASS" signature="cleanUp()" name="cleanUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="setUp()" name="setUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="PASS" signature="aTest()" name="aTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
      </class>
      <class name="test.SetUpTest">
        <test-method status="FAIL" signature="setUp()" name="setUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at test.SetUpTest.setUp(SetUpTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:580)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:398)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:145)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:82)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:167)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:823)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:790)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.testng.TestNG.privateMain(TestNG.java:860)
	at org.testng.TestNG.main(TestNG.java:833)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="SKIP" signature="aTest()" name="aTest" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
        <test-method status="SKIP" signature="cleanUp()" name="cleanUp" is-config="true" duration-ms="0" started-at="2008-11-21T21:43:50Z" finished-at="2008-11-21T21:43:50Z">
        </test-method>
      </class>
    </test>
    <test>
      <class name="test.SkippedExceptionTest">
        <test-method status="SKIP" signature="fexTest()" name="fexTest" duration-ms="0" started-at="2008-11-21T17:59:38Z" finished-at="2008-11-21T17:59:38Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
